################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
usblib/host/usbhaudio.obj: ../usblib/host/usbhaudio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhaudio.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhhid.obj: ../usblib/host/usbhhid.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhhid.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhhidkeyboard.obj: ../usblib/host/usbhhidkeyboard.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhhidkeyboard.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhhidmouse.obj: ../usblib/host/usbhhidmouse.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhhidmouse.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhhub.obj: ../usblib/host/usbhhub.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhhub.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhmsc.obj: ../usblib/host/usbhmsc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhmsc.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhostenum.obj: ../usblib/host/usbhostenum.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhostenum.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/host/usbhscsi.obj: ../usblib/host/usbhscsi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/host/usbhscsi.pp" --obj_directory="usblib/host" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


