################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
utils/cmdline.obj: C:/ti/TivaWare_C_Series-2.1.1.71/utils/cmdline.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/cmdline.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/cpu_usage.obj: ../utils/cpu_usage.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/cpu_usage.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/eeprom_pb.obj: ../utils/eeprom_pb.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/eeprom_pb.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/flash_pb.obj: ../utils/flash_pb.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/flash_pb.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/isqrt.obj: ../utils/isqrt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/isqrt.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/random.obj: ../utils/random.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/random.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/ringbuf.obj: ../utils/ringbuf.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/ringbuf.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/scheduler.obj: ../utils/scheduler.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/scheduler.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/sine.obj: ../utils/sine.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/sine.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/smbus.obj: ../utils/smbus.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/smbus.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/softi2c.obj: ../utils/softi2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/softi2c.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/softssi.obj: ../utils/softssi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/softssi.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/softuart.obj: ../utils/softuart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/softuart.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/spi_flash.obj: ../utils/spi_flash.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/spi_flash.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/uartstdio.obj: C:/ti/TivaWare_C_Series-2.1.1.71/utils/uartstdio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/uartstdio.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

utils/ustdlib.obj: C:/ti/TivaWare_C_Series-2.1.1.71/utils/ustdlib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="utils/ustdlib.pp" --obj_directory="utils" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


