################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
usblib/device/usbdaudio.obj: ../usblib/device/usbdaudio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdaudio.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdbulk.obj: ../usblib/device/usbdbulk.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdbulk.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdcdc.obj: ../usblib/device/usbdcdc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdcdc.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdcdesc.obj: ../usblib/device/usbdcdesc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdcdesc.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdcomp.obj: ../usblib/device/usbdcomp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdcomp.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdconfig.obj: ../usblib/device/usbdconfig.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdconfig.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbddfu-rt.obj: ../usblib/device/usbddfu-rt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbddfu-rt.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdenum.obj: ../usblib/device/usbdenum.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdenum.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdhandler.obj: ../usblib/device/usbdhandler.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdhandler.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdhid.obj: ../usblib/device/usbdhid.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdhid.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdhidgamepad.obj: ../usblib/device/usbdhidgamepad.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdhidgamepad.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdhidkeyb.obj: ../usblib/device/usbdhidkeyb.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdhidkeyb.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdhidmouse.obj: ../usblib/device/usbdhidmouse.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdhidmouse.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

usblib/device/usbdmsc.obj: ../usblib/device/usbdmsc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/ti/TivaWare_C_Series-2.1.1.71/examples/boards/ek-tm4c1294xl-boost-cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/drivers/ek-tm4c129" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/ff11a" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/usblib" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/core_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver/include" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/host_driver" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/spi" --include_path="C:/Users/Al/workspace_v6_1/cc3000_basic_wifi_application/cc3000/src/uart" -g --gcc --define=ccs="ccs" --define=PART_TM4C1294NCPDT --define=CC3000_USE_BOOSTERPACK2 --define=_POSIX_SOURCE --define=TARGET_IS_TM4C129_RA0 --define=CC3000_TM4C129_SPI --define=UART_BUFFERED --display_error_number --diag_wrap=off --diag_warning=225 --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="usblib/device/usbdmsc.pp" --obj_directory="usblib/device" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


